[package]
name = "elven-nft-minter"
version = "1.5.1"
authors = ["Julian Ä†wirko <julian.cwirko@gmail.com>"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.28.0"
features = ["cb_closure_managed_deser"]

[dev-dependencies.elrond-wasm-debug]
version = "0.28.0"

[dev-dependencies]
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"
