[package]
name = "elven-nft-minter-meta"
version = "1.2.0"
authors = ["Julian Ä†wirko <julian.cwirko@gmail.com>"]
edition = "2018"
publish = false

[dependencies.elven-nft-minter]
path = ".."

[dependencies.elrond-wasm]
version = "0.27.4"

[dependencies.elrond-wasm-debug]
version = "0.27.4"
