[package]
name = "elven-nft-minter-meta"
version = "1.7.0"
authors = ["Julian Ä†wirko <julian.cwirko@gmail.com>"]
edition = "2018"
publish = false

[dependencies.elven-nft-minter]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.32.0"
