[package]
name = "elven-nft-minter-meta"
version = "1.13.0"
authors = ["Julian Ä†wirko <julian.io>"]
edition = "2021"
publish = false

[dependencies.elven-nft-minter]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.41.2"
